#ifndef LABIRINTH_CONSTANTS
#define LABIRINTH_CONSTANTS

#define NICKNAME_LENGTH 16
#define RESPONSE_LENGTH 256

#define PIXEL_SIZE 40
#define TILE_SIZE_IN_PIXELS 8
#define TILE_SIZE (PIXEL_SIZE * TILE_SIZE_IN_PIXELS)

#define DRAW_SIZE 8

// gameplay params
#define PLAYER_SPEED 40

// arena map params
#define ARENA_WALLS "-|+"
#define ARENA_WIDTH_IN_TILES 36
#define ARENA_HEIGHT_IN_TILES 30
#define ARENA_HEIGHT (ARENA_HEIGHT_IN_TILES*TILE_SIZE)
#define ARENA_WIDTH (ARENA_WIDTH_IN_TILES*TILE_SIZE)

// more colors in 256
#define COLOR_BLACK_DARK 16
#define COLOR_GRAY 233
#define COLOR_YELLOW_BRIGHT 11
#define COLOR_ORANGE 173

#define JOIN_GAME '0'
#define MOVE '1'
#define LOBBY_INFO '2'
#define GAME_IN_PROGRESS '3'
#define USERNAME_TAKEN '4'
#define GAME_START '5'
#define MAP_ROW '6'
#define GAME_UPDATE '7'
#define PLAYER_DEAD '8'
#define GAME_END '9'

#endif